version: '2'
services:
  postgres:
    container_name: postgres-citibike
    restart: always
    image: postgres:10.5
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
volumes:
    pgdata:
